apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: [{{ .Values.nodePool.capacityType | quote }}]
        - key: kubernetes.io/arch
          operator: In
          values: [{{ .Values.nodePool.arch | quote }}]
        {{- if hasSuffix "-gpu" .Values.nodeVariant }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - "p"
            - "g"
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        {{- else if hasSuffix "-neuron" .Values.nodeVariant }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - "inf"
            - "trn"
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["0"]
        {{- else }}
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
          {{- range .Values.nodePool.instanceTypes }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
  limits:
    cpu: {{ .Values.nodePool.cpuLimit | quote }}
    memory: {{ .Values.nodePool.memoryLimit | quote }}
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: {{ .Values.nodePool.consolidateAfter | quote }}
